apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: react-app
        image: react-nginx-tre:latest
        command: ["nginx", "-g", "daemon off;"]
        imagePullPolicy: Never
        resources:
          limits:
            cpu: "500m"
            memory: "128Mi"
        ports:
        - containerPort: 80


---

apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  selector:
    app: react-app
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
